need to change __init__, because I got a error like 'AttributeError: 'NoneType' object has no attribute 'login_a_conn'', it seems that I need to build a conn inside __init__ rather than inside a normal child function